FROM python:3.10.13-slim

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN apt-get update --fix-missing && \
    apt-get install -y vim wget bzip2 curl git build-essential&& \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#  apt-get upgrade 
#  python3-capstone libpq-dev 

RUN mkdir /app
WORKDIR /app

COPY requirements.txt ./

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt